version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - $PWD/data:/var/lib/postgresql/data
      # - postgres_data:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4
  #   restart: always
  #   ports:
  #     - "8432:80"
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=pgadmin4@hotmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #   volumes:
  #     - pgadmin4-data:/var/lib/pgadmin
# volumes:
  # postgres_data:
  # pgadmin4-data:
